spring.application.name=todo-app
server.port=8080

# Swagger - Configuración GENERAL (para todos los entornos)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json